# Generated by Django 5.2.11 on 2026-02-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Chairman", "Chairman"),
                    ("Director", "Director"),
                    ("Principal", "Principal"),
                    ("HOD", "HOD"),
                    ("Mentor", "Mentor"),
                    ("Faculty", "Faculty"),
                    ("Student", "Student"),
                    ("Parent", "Parent"),
                    ("HR", "HR"),
                    ("Placement", "Placement"),
                ],
                max_length=20,
            ),
        ),
    ]
