# Generated by Django 5.2.11 on 2026-03-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Director", "Director"),
                    ("Examcell", "Exam Cell"),
                    ("HOD", "HOD"),
                    ("Mentor", "Mentor"),
                    ("Faculty", "Faculty"),
                    ("Student", "Student"),
                    ("Parent", "Parent"),
                ],
                max_length=20,
            ),
        ),
    ]
