# Generated by Django 5.2.12 on 2026-03-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="category",
            field=models.CharField(
                choices=[
                    ("News", "Campus News"),
                    ("Exam", "Exam Cell Update"),
                    ("Event", "Stories of Success"),
                ],
                default="News",
                max_length=20,
            ),
        ),
    ]
