# Generated by Django 5.2.11 on 2026-03-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="target_role",
            field=models.CharField(
                choices=[
                    ("All", "All"),
                    ("Director", "Director"),
                    ("Examcell", "Exam Cell"),
                    ("Student", "Student"),
                    ("Faculty", "Faculty"),
                    ("HOD", "HOD"),
                    ("Mentor", "Mentor"),
                    ("Parent", "Parent"),
                ],
                default="All",
                max_length=20,
            ),
        ),
    ]
