# Generated by Django 5.2.11 on 2026-02-20 18:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='verified',
        ),
        migrations.AddField(
            model_name='certification',
            name='cert_type',
            field=models.CharField(choices=[('link', 'External Link (Credly/Exam Center)'), ('upload', 'Manual Upload'), ('college', 'College Issued')], default='upload', max_length=10),
        ),
        migrations.AddField(
            model_name='certification',
            name='cert_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='certification',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certification',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='certification',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cert_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('college', 'College Supervised'), ('external', 'External')], default='external', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='team_size',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='codechef_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='codeforces_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='github_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='hackerrank_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='leetcode_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='personal_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='personal_phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='certifications/'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='issuer',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='certification',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=300)),
                ('source', models.CharField(choices=[('faculty', 'Faculty (College)'), ('nptel', 'NPTEL'), ('external', 'External (Udemy/Coursera etc.)')], default='external', max_length=10)),
                ('platform', models.CharField(blank=True, default='', max_length=100)),
                ('completion_percentage', models.PositiveIntegerField(default=100)),
                ('certificate_url', models.URLField(blank=True, default='')),
                ('is_verified', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='students.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=300)),
                ('scope', models.CharField(choices=[('College', 'College'), ('External', 'External')], max_length=10)),
                ('role', models.CharField(choices=[('Participation', 'Participation'), ('Award', 'Award'), ('Position', 'Position')], max_length=15)),
                ('position', models.CharField(blank=True, default='', max_length=100)),
                ('organizer', models.CharField(blank=True, default='', max_length=200)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('event_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='students.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('organization', models.CharField(max_length=300)),
                ('role', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('technologies', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('supervisor_name', models.CharField(blank=True, default='', max_length=200)),
                ('supervisor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='internship_certs/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='students.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('research_type', models.CharField(choices=[('college', 'College Collaborated'), ('external', 'External')], max_length=10)),
                ('title', models.CharField(max_length=400)),
                ('advisor_name', models.CharField(blank=True, default='', max_length=200)),
                ('advisor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('outcome', models.CharField(choices=[('paper', 'Research Paper'), ('book', 'Book'), ('other', 'Other')], default='paper', max_length=10)),
                ('publisher', models.CharField(blank=True, default='', max_length=300)),
                ('publication_url', models.URLField(blank=True, default='')),
                ('published_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research', to='students.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EducationBackground',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('edu_type', models.CharField(choices=[('SSC', '10th / SSC'), ('Inter', 'Intermediate (12th)'), ('Diploma', 'Diploma'), ('EAMCET', 'AP/TS EAMCET Rank'), ('ECET', 'ECET Rank')], max_length=20)),
                ('institution', models.CharField(blank=True, default='', max_length=300)),
                ('board_university', models.CharField(blank=True, default='', max_length=200)),
                ('year_of_passing', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.CharField(blank=True, default='', max_length=20)),
                ('score_type', models.CharField(choices=[('%', 'Percentage'), ('GPA', 'GPA'), ('Rank', 'Rank')], default='%', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='students.studentprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edu_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'edu_type')},
            },
        ),
    ]
